### PR TITLE
Dockerized project

### LINKED ISSUE #71: Make a Dockerfile for the app
It would be awesome to be able to have haskell.do in a docker container so a user could isolate all their environment.

### PR DESCRIPTION
**Pull request by ocramz**
Meant to fix #71

### CODE REVIEW

**Review by NickSeagull — APPROVED** [review]
Great, thank you very much!! Are you currently using Haskell.do?

**Comment by NickSeagull** [comment]
TravisCI complains with:

```text
$ docker build -t theam/haskell-do src/docker/
Sending build context to Docker daemon  4.096kB
Error response from daemon: Dockerfile parse error line 3: unknown instruction: TAG
```

Any idea @ocramz ?

**Comment by ocramz** [comment]
uhh I must have a different version of docker, will look later today. TTYL!

Edit: no, simply the `TAG` command is not allowed in a Dockerfile (you can only tag an image when building it from command line).

**Comment by ocramz** [comment]
* fix Dockerfile
* add makefile
* add instructions in README

**Comment by NickSeagull** [comment]
Great! Thanks!

**Pull request merged**
