### PR TITLE
use the `stack` installation in env instead of an absolute path - solves #60

### PR DESCRIPTION
**Pull request by mdibaiee**
solves #60

### CODE REVIEW

**Comment by NickSeagull** [comment]
Looks cool, does Windows have a `where` command? It would be cool to make a step in the right direction. :)

**Comment by mdibaiee** [comment]
@NickSeagull well, now that I think of it, why don't we just use the `stack` in the environment? I mean we don't have to specify the full path, do we? `stack new ...` should do, hmm? :grin:

**Comment by NickSeagull** [comment]
True, stack itself will do

**Comment by mdibaiee** [comment]
@NickSeagull turned out to be much simpler, rebased

**Comment by NickSeagull** [comment]
Awesome, will merge it ASAP, gonna generate a new build with these changes soon.

**Review by NickSeagull — APPROVED** [review]
Thanks!

**Pull request merged**
