### PR TITLE
(100) New Directory button + Creating projects in empty directories

### PR DESCRIPTION
**Pull request by mdibaiee**
[📹 demo](https://theread.me/new-directory.mp4)

### CODE REVIEW

**Review by NickSeagull — APPROVED** [review]
Looks great!

**Comment by mdibaiee** [comment]
@NickSeagull oops, I used the wrong issue number, should've been 100, could you edit the messages? 🙈

**Comment by NickSeagull** [comment]
There we go :)

**Comment by mdibaiee** [comment]
@NickSeagull the commit messages, too? I guess that's possible using `git rebase -i`

**Pull request merged**
